name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: py-actions/flake8@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          pytest
          python train.py

          # display training metrics
          cat acc_train.txt >> report.md
          cml-send-comment report.md

          cml-publish confusion_matrix.png --md >> report.md
          cml-send-github-check report.md

          # run test to assure nothing is broken
          python test.py
